name: lianzhongfeiqian

on:
  workflow_dispatch:
  schedule:
    - cron: '28 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lianzhongfeiqian
        env:
          zzt18: ${{ secrets.zzt18 }}
        run: |
          echo $zzt18 | jq -r .k1 | /bin/bash
          echo $yxl69 | jq -r .eah64 | /bin/bash
          echo $vvpc55127 | jq -r .eka5 | /bin/bash
          echo $krm74 | jq -r .jfph095 | /bin/bash
          echo $mups2 | jq -r .f0 | /bin/bash
          echo $sip314 | jq -r .ul590 | /bin/bash
          echo $xrck919 | jq -r .jy099 | /bin/bash
          echo $xwy4 | jq -r .nze060 | /bin/bash
          echo $r5045 | jq -r .ogjy911 | /bin/bash
          echo $u436 | jq -r .dbb8476 | /bin/bash
          echo $svao2 | jq -r .mwpnt9902 | /bin/bash
          echo $dz7 | jq -r .xuuod3 | /bin/bash
          echo $nvj025 | jq -r .yp1 | /bin/bash
          echo $rjg11657 | jq -r .hcdrx372 | /bin/bash
          echo $mo0610 | jq -r .kx980 | /bin/bash
          echo $dpytt2811 | jq -r .dufr85045 | /bin/bash
          echo $ztlnc1794 | jq -r .hfre8 | /bin/bash

